### PR TITLE
chore(deps): upgrade to latest stable

### PR DESCRIPTION
**Pull request by AviVahl**
Upgrade deps to latest stable and regenerate lock file

### CODE REVIEW

**Comment by AviVahl** [comment]
@alisey can anybody from your team check this out?

**Review by alisey — APPROVED** [review]
In this repo we use the `development` branch for PRs instead of `main`, because `main` goes straight to the users.

**Comment by AviVahl** [comment]
> In this repo we use the `development` branch for PRs instead of `main`, because `main` goes straight to the users.

when does the `development` branch get merged back to `main`? Who's doing it? When?

**Comment by alisey** [comment]
> when does the development branch get merged back to main? Who's doing it? When?

Manually once in a while after validation. We've never done it yet.

**Comment by alisey** [comment]
You've merged into `main` BTW.

**Comment by AviVahl** [comment]
Ah I thought you approved as an exception. Noted for next time.

**Pull request merged**
